name: pixel_canvas
version: 1.2.0
author: Keiichiro Ui <keiichiro.ui@gmail.com>
description: A canvas custom element to render/edit pixels
homepage: https://github.com/kui/pixel_canvas
environment:
  sdk: '>=1.11.0'
dependencies:
  polymer: '>=0.16.0 <0.17.0'
dev_dependencies:
  ghpages_generator: '>=0.3.0 <0.4.0'
  test: '>=0.12.0 <0.13.0'
transformers:
- polymer:
    entry_points:
    - example/index.html
