name: pixel_canvas
version: 1.1.0
author: Keiichiro Ui <keiichiro.ui@gmail.com>
description: A canvas custom element to render/edit pixels
homepage: https://github.com/kui/pixel_canvas
environment:
  sdk: '>=1.6.0'
dependencies:
  polymer: '>=0.13.0 <0.14.0'
dev_dependencies:
  ghpages_generator: '>=0.2.0 <0.3.0'
  path: '>=1.2.0 <1.3.0'
  unittest: '>=0.11.0 <0.12.0'
transformers:
- polymer:
    entry_points:
    - example/index.html
