name: pixel_canvas_sample
description: A sample Polymer application
dependencies:
  polymer: any
  pixel_canvas:
    path: '..'
transformers:
- polymer:
    entry_points: web/pixel_canvas_sample.html
